

dbt-models:
  target: pr
  outputs:
    pr:
      type: bigquery
      method: service-account
      project: "${{ env_var('DBT_GOOGLE_BIGQUERY_PROJECT')}}" 
      dataset: "${{ env_var('DBT_GOOGLE_BIGQUERY_DATASET_PR')}}"
      threads: 4
      keyfile: ${{ secrets.DBT_GOOGLE_BIGQUERY_KEYFILE}}
      location: europe-southwest1
    prod:
      type: bigquery
      method: service-account
      project: "${{ env_var('DBT_GOOGLE_BIGQUERY_PROJECT')}}" 
      dataset: "${{ env_var('DBT_GOOGLE_BIGQUERY_DATASET_PR')}}"
      threads: 4
      keyfile: "${{ env_var('DBT_GOOGLE_BIGQUERY_KEYFILE')}}"
      location: europe-southwest1 
