

dbt-models:
  target: pr
  outputs:
    pr:
      type: bigquery
      method: service-account
      project: dezoomcamp-2023-375020
      dataset: ${{ secrets.DBT_GOOGLE_BIGQUERY_DATASET_PR }}
      threads: 4
      keyfile: ${{secrets.DBT_GOOGLE_BIGQUERY_KEYFILE}}
      location: europe-southwest1
    prod:
      type: bigquery
      method: service-account
      project: ${{ secrets.DBT_GOOGLE_BIGQUERY_PROJECT }}
      dataset: ${{ secrets.DBT_GOOGLE_BIGQUERY_DATASET_PROD }}
      threads: 4
      keyfile: ${{secrets.DBT_GOOGLE_BIGQUERY_KEYFILE}}
      location: europe-southwest1 
